package io.github.darkstarworks.pluginpulse.inject;

/** Builds the {@code pluginpulse.yml} text embedded into an injected jar. */
final class PulseYaml {

    private PulseYaml() {
    }

    static String build(InjectOptions o) {
        StringBuilder sb = new StringBuilder();
        sb.append("# Generated by pluginpulse-inject.\n");
        if (InjectOptions.notBlank(o.modrinth())) sb.append("modrinth: ").append(o.modrinth()).append('\n');
        if (InjectOptions.notBlank(o.github())) sb.append("github: ").append(o.github()).append('\n');
        if (InjectOptions.notBlank(o.hangar())) sb.append("hangar: ").append(o.hangar()).append('\n');
        if (InjectOptions.notBlank(o.permission())) sb.append("permission: ").append(o.permission()).append('\n');
        if (InjectOptions.notBlank(o.commandRoot())) sb.append("command-root: ").append(o.commandRoot()).append('\n');
        if (InjectOptions.notBlank(o.userAgentContact()))
            sb.append("user-agent-contact: \"").append(o.userAgentContact()).append("\"\n");
        sb.append("mode: ").append(InjectOptions.notBlank(o.mode()) ? o.mode() : "notify").append('\n');
        if (o.checkIntervalHours() != null) sb.append("check-interval-hours: ").append(o.checkIntervalHours()).append('\n');
        if (InjectOptions.notBlank(o.track())) sb.append("track: ").append(o.track()).append('\n');
        return sb.toString();
    }
}
